# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from profile import service_pb2 as profile_dot_service__pb2


class ProfileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProfile = channel.unary_unary(
                '/profile.ProfileService/GetProfile',
                request_serializer=profile_dot_service__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=profile_dot_service__pb2.GetProfileResponse.FromString,
                )
        self.SerProfile = channel.unary_unary(
                '/profile.ProfileService/SerProfile',
                request_serializer=profile_dot_service__pb2.SetProfileRequest.SerializeToString,
                response_deserializer=profile_dot_service__pb2.SetProfileResponse.FromString,
                )


class ProfileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SerProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=profile_dot_service__pb2.GetProfileRequest.FromString,
                    response_serializer=profile_dot_service__pb2.GetProfileResponse.SerializeToString,
            ),
            'SerProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.SerProfile,
                    request_deserializer=profile_dot_service__pb2.SetProfileRequest.FromString,
                    response_serializer=profile_dot_service__pb2.SetProfileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profile.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ProfileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.ProfileService/GetProfile',
            profile_dot_service__pb2.GetProfileRequest.SerializeToString,
            profile_dot_service__pb2.GetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SerProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/profile.ProfileService/SerProfile',
            profile_dot_service__pb2.SetProfileRequest.SerializeToString,
            profile_dot_service__pb2.SetProfileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
