apiVersion: v1
kind: Service
metadata:
  name: obs-odigos-public
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: obs
    app.kubernetes.io/name: odigos
  type: LoadBalancer