apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dummy-score-service.name }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.dummy-score-service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.dummy-score-service.replicaCount }}
  selector:
    {{- with .Values.dummy-score-service.labels }}
    matchLabels:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.dummy-score-service.labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      containers:
        - name: {{ .Values.dummy-score-service.name }}
          image: {{ .Values.dummy-score-service.image }}
          ports:
            - name: http
              containerPort: {{ .Values.dummy-score-service.port }}
              protocol: TCP