apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-configmap
data:
  migration0001.sql: |
    \c profservice;
    CREATE TABLE profiles (
        id SERIAL PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT NOW()
    )
