apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dummygateway.name }}-public-service
  namespace: {{ .Values.namespace }}
  {{- with .Values.dummygateway.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: {{ .Values.dummygateway.port }}
      protocol: TCP
  {{- with .Values.dummygateway.labels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
