namespace: dummy-app-development

dummygateway:
  name: dummy-gateway
  image: 322456/dummy-gateway-remote:latest
  replicas: 1
  port: 80
  labels:
    app: dummy-gateway
    env: development

dummyscoreservice:
  name: dummy-score-service
  image: 322456/dummy-score-service:0.2
  replicas: 1
  port: 8081
  labels:
    app: dummy-score-service
    env: development
  database:
    image:  mongo:latest
    port: 27017
    labels:
      app: dummy-score-service-database
      env: development

dummyprofileservice:
  name: dummy-profile-service
  image: 322456/dummy-profile-service-remote:latest
  replicas: 1
  port: 8089
  labels:
    app: dummy-profile-service
    env: development
  database:
    image: postgres:latest
    port: 5432
    labels:
      app: dummy-score-service-database
      env: development