    exporters:
      jaeger:
        endpoint: 'autoinstrumentation-playground-jaeger-1:14250'
        tls:
          insecure: true
      logging: {}
    extensions:
      health_check: {}
      memory_ballast:
        size_in_percentage: 40
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
              - http://*
    service:
      extensions:
      - health_check
      pipelines:
        logs:
          exporters:
          - logging
          processors: []
          receivers:
          - otlp
        metrics:
          exporters:
          - logging
          processors: []
          receivers:
          - otlp
        traces:
          exporters:
          - jaeger
          processors: []
          receivers:
          - otlp
      telemetry:
